### ISSUE TITLE
Cùng viết blog KTMT

### ISSUE THREAD

**Issue by ngocdaothanh** [ktmt/ktmtblog-octopress#2]
Mình (sẽ rủ thêm vài bạn khác, ví dụ @cmpitg) muốn cùng tham gia viết bài cho blog KTMT.

Xin hỏi blog KTMT có qui chế hay là guide gì đó để công khai, minh bạch hóa về việc này k? Nếu chưa có thì định hướng về việc này như thế nào?

**Comment by cmpitg** [comment]
@ngocdaothanh +1

**Comment by huydx** [comment]
Hi anh @ngocdaothanh , @cmpitg 

Blog ktmt rất vui khi nhận được lời đề nghị đóng góp bài của 2 anh. Hiện tại, nhóm hoàn toàn không có một qui chế cụ thể nào về cách đóng góp bài cũng như nội dung bài viết cho ktmt. 

Tuy nhiên khi nhận được lời đề nghị của 2 anh, bọn em đã thử suy nghĩ và đưa ra phương thức đóng góp trước mắt như sau. Phương thức này nếu thống nhất, sẽ được dùng để làm hướng dẫn cho những bạn mới sau này muốn viết cùng ktmt.

Cách đóng góp: 
 - Gửi nội dung bài viết mới dưới dạng PR.
 - Tất cả cùng review. 
 - Khi người viết sửa hết comment, bọn em sẽ deploy lên ktmt.github.io 

Cách đóng góp bài viết cho ktmt như [link](ktmt.github.io/blog/2013/04/30/huong-dan-su-dung-octopress-cho-blog-tren-github/).

Bài viết có thể về mọi chủ đề, miễn là gói gọn trong các vấn đề kỹ thuật và được đầu tư thời gian 

Nếu 2 anh thấy có cách nào hay hơn, anh hãy đưa ra ý kiến nhé. Rất hy vọng blog ktmt sẽ có thêm các bài viết chất lượng từ 2 anh.

**Comment by ngocdaothanh** [comment]
Anh nghĩ qui chế trên về định hướng cũng ổn.
Qua thời gian sẽ cải tiến thêm.

Góp ý:

Chỗ "Tất cả cùng review" có vẻ mơ hồ, k rõ ai sẽ review, khi nào bài sẽ được đăng. Nên chăng sửa như sau:

Sau khi có ít nhất một core member review, bài viết sẽ được đăng. Trong quá trình review có thể tác giả sẽ được góp ý để cải tiến thêm bài viết.

Nên có danh sách core member (kiểu như ban biên tập) để người đọc biết những người có trách nhiệm là ai.

Ngoài ra nên có thêm qui chế sau khi đăng ví dụ 3, 5, hoặc 10 bài thì sẽ được mời làm core member.

Sau khi qui chế ổn ổn thì @huydx viết qui chế thành một bài đàng hoàng, post lên http://ktmt.github.io/, rồi thêm link vào side bar bên trái trang web nhé.

**Comment by cmpitg** [comment]
Em nghĩ trước mắt mình có thể bắt đầu mọi thứ đơn giản:

* Đóng góp bài viết bằng PR
* Ít nhất một người trong core team sẽ review
* Sau khi các comment đã được sửa, bài viết được approved và đăng

Mình có thể hệ thống hóa lại sau này khi số lượng bài viết hoặc số lượng người đóng góp nhiều.

**Comment by huydx** [comment]
Hi @ngocdaothanh  và @cmpitg  lý do và qui chế về việc mở ktmt blog đã được tổng hợp thành bài viết và đã được deploy theo đường link dưới đây:
[http://ktmt.github.io/blog/2015/03/08/ktmt-blog-nguon-mo](http://ktmt.github.io/blog/2015/03/08/ktmt-blog-nguon-mo/) 

2 người confirm và nếu có ý kiến gì để làm cho việc đóng góp/review trở nên dễ dàng hơn thì có thể comment ở đây nhé.

**Comment by ngocdaothanh** [comment]
:+1:

**Comment by ngocdaothanh** [comment]
:+1: 
Có thuật ngữ để miêu tả blog dạng này: bliki (blog + wiki).
http://www.martinfowler.com/bliki/WhatIsaBliki.html

**Comment by huydx** [comment]
@ngocdaothanh :+1: , cám ơn anh, em nghĩ bliki là một khái niệm rất thú vị :) . Vậy chúng ta có thể đóng issue này lại được rồi nhỉ, rất mong sẽ nhận được những bài đóng góp từ anh sớm!

**Comment by cmpitg** [comment]
:+1:

Vâng, em nghĩ mình có thể đóng issue này được rồi.

**Comment by ngocdaothanh** [comment]
Mình đóng issue nhé.
Ban biên tập thêm link đến thông báo trên vào side bar của trang chủ nhé.
